### ISSUE TITLE
OTHire Console Error

### ISSUE THREAD

**Issue by Tetee11** [slawkens/myaac-gesior-shop-system#1]
`Lua Script Error: [GlobalEvent Interface]
data/globalevents/scripts/gesior-shop-system.lua:onThink

data/globalevents/scripts/gesior-shop-system.lua:49: attempt to call method 'sav
e' (a nil value)
stack traceback:
        data/globalevents/scripts/gesior-shop-system.lua:49: in function 'doPlay
erSave'
        data/globalevents/scripts/gesior-shop-system.lua:212: in function <data/
globalevents/scripts/gesior-shop-system.lua:149>
[Error - GlobalEvents::think] Failed to execute event: gesior-shop-system`

**Comment by slawkens** [comment]
Thanks for this report. I will look into this today after work.

Sorry for the delay, I was pretty busy.

**Comment by slawkens** [comment]
This has been just fixed.

Please try this: https://github.com/slawkens/myaac-gesior-shop-system/blob/master/gesior-shop-system.lua

**Comment by Tetee11** [comment]
Working!!

**Comment by slawkens** [comment]
Cool! =)

Closing this then.
