### ISSUE TITLE
Full history of premium points for admin

### ISSUE THREAD

**Issue by whiteblXK** [slawkens/myaac-gesior-shop-system#2]
Hello, can you write a plugin which I can see whole logs of premium points for each players? Monthly earnings from all transaction websites(paypal etc.). Something through which I will be able to view everything that what happens with premium points.

**Comment by slawkens** [comment]
Yes, I can write.

But it won't have the highest priority, so you will need to wait sometime, unless you pay me to do the express work :)

**Comment by slawkens** [comment]
I suppose now you have enought knowledge to write it yourself :)
