### ISSUE TITLE
Donate isn't delivering Points to the accounts.

### ISSUE THREAD

**Issue by d0gw4r** [slawkens/myaac-gesior-shop-system#4]
Hi,

Someone made a donation through the PagSeguro method, I received the confirmation of the payment on my e-mail, but the points aren't being delivered to the person account, nor at least shows if someone generated a ticket, and that is awaiting payment, etc, there on my phpmyadmin page.

As my admin account has points, I tested it when I use them in the shop the items arrive, and they are arriving in the game normally, the only problem is with the delivery of the points itself when someone makes me a donation.

Take a look,

![image](https://user-images.githubusercontent.com/51352360/59364365-2072da80-8d0d-11e9-9a7f-114d6e9f3ad6.png)

This is my PagSeguro configuration in **/plugins/gesior-shop-system/config.php** directory.

`/**
 * PagSeguro configuration
 */
$config['pagseguro'] = array(
	'enabled' => true,
	'email' => 'gui.lgsouza94@gmail.com',
	'environment' => 'production', // production, sandbox
	'token' => array(
		'production' => 'HIDE',
		'sandbox' => '',
	),
	'urlRedirect' => '?subtopic=points&action=final', // default should be good
	'productName' => 'Premium Points', // or Coins
	'productValue' => 1.00,
	'doublePoints' => false, // should points be doubled? for example: for 5 points donated you become 10.
	'options' => array( // cost => points/coins
		'5,00' => 5,
		'10,00' => 10,
		'20,00' => 20,
		'40,00' => 40,
		'60,00' => 60,
		'120,00' => 120,
	)
);`

**Comment by d0gw4r** [comment]
~EDIT~

It appears on pagseguro_transactions table, but still don't delivering points to the account who donated.

![image](https://user-images.githubusercontent.com/51352360/59366612-f3c0c200-8d10-11e9-8e12-4be88ed3626f.png)

**Comment by Ackerzin** [comment]
Mine is the same way, paid, but the points are not delivered.

![image](https://user-images.githubusercontent.com/25888022/61508520-a8a96700-a9c0-11e9-8e6a-9748c034fa37.png)

**Comment by gabz182** [comment]
same shit here.
i surrender this site.  ¬¬

**Comment by mattos123** [comment]
here's the solution
/payments/pagseguro.php
go to line 57 
replace with this
`$field = "coins";

									$stmt = $conn->prepare('UPDATE accounts SET ' . $field . ' = ' . $field . ' + :item_count WHERE ' . (USE_ACCOUNT_NAME ? 'name' : 'id') . ' = :account');`

**Comment by tobi132** [comment]
It has been already fixed.

Here's the link to the newest version: https://github.com/slawkens/myaac-gesior-shop-system/releases/latest
